export const categories = [
  { id: 'romantic', name: 'Love & Romance', emoji: '❤️', color: 'rose' },
  { id: 'funny', name: 'Vibes', emoji: '😂', color: 'orange' },
  { id: 'deep', name: 'Deep Talks', emoji: '🧠', color: 'indigo' },
];

// ... (categories array stays same)

export const questions = {
  romantic: [
    { id: 1, text: "Who sends 'Have you eaten?' texts more?", options: ["Me", "Partner", "Both equally"] },
    { id: 2, text: "Who posts the other on WhatsApp status more?", options: ["Me", "Partner", "We are lowkey"] },
    { id: 3, text: "Who is more likely to pay for dates?", options: ["Me", "Partner", "We split (50/50)"] },
    { id: 4, text: "Who cooks the best Jollof Rice?", options: ["Me", "Partner", "We order food"] },
    { id: 5, text: "Who is the 'Hard Guy/Babe' that is actually soft inside?", options: ["Me", "Partner", "Both"] },
    { id: 6, text: "Who gets jealous faster?", options: ["Me", "Partner", "Neither"] },
    { id: 7, text: "Who is more likely to buy thoughtful gifts?", options: ["Me", "Partner", "Equal"] },
    { id: 8, text: "Who initiates the 'What are we?' conversation?", options: ["Me", "Partner", "It just happened"] },
    { id: 9, text: "Who says 'I love you' more?", options: ["Me", "Partner", "Equal"] },
    { id: 10, text: "Who is more affectionate in public (PDA)?", options: ["Me", "Partner", "We don't do that outside"] },
    { id: 11, text: "Who apologizes first after a fight?", options: ["Me", "Partner", "Whoever is wrong"] },
    { id: 12, text: "Who is more patient?", options: ["Me", "Partner", "Neither lol"] },
    { id: 13, text: "Who remembers anniversaries/dates better?", options: ["Me", "Partner", "Both forget"] },
    { id: 14, text: "Who is more likely to plan a surprise date?", options: ["Me", "Partner", "Neither"] },
    { id: 15, text: "Who calls more often?", options: ["Me", "Partner", "Texting only"] },
    { id: 16, text: "Who is more clingy?", options: ["Me", "Partner", "Neither"] },
    { id: 17, text: "Who initiates romance/intimacy more?", options: ["Me", "Partner", "Equal"] },
    { id: 18, text: "Who is better at comforting the other when sad?", options: ["Me", "Partner", "Both"] },
    { id: 19, text: "Who is more possessive ('My property')?", options: ["Me", "Partner", "Neither"] },
    { id: 20, text: "Who compliments the other's outfit more?", options: ["Me", "Partner", "Equal"] },
    { id: 21, text: "Who is more likely to bring up marriage?", options: ["Me", "Partner", "We avoid the topic"] },
    { id: 22, text: "Who handles long-distance better?", options: ["Me", "Partner", "We would break up"] },
    { id: 23, text: "Who will be the 'fun parent'?", options: ["Me", "Partner", "Both strict"] },
    { id: 24, text: "Who takes more pictures of the other?", options: ["Me", "Partner", "Equal"] },
    { id: 25, text: "Who is more likely to write a love letter/paragraph?", options: ["Me", "Partner", "Both"] },
    { id: 26, text: "Who falls in love faster?", options: ["Me", "Partner", "Same speed"] },
    { id: 27, text: "Who is nicer to the other's friends?", options: ["Me", "Partner", "Equal"] },
    { id: 28, text: "Who is more likely to cry during a movie?", options: ["Me", "Partner", "Neither"] },
    { id: 29, text: "Who uses pet names (Baby, Champ, etc.) more?", options: ["Me", "Partner", "We use real names"] },
    { id: 30, text: "Who gives better massages?", options: ["Me", "Partner", "Neither"] }
  ],
  funny: [
    { id: 1, text: "Who is always late ('I'm coming')?", options: ["Me", "Partner", "African time is real"] },
    { id: 2, text: "Who is more likely to 'bill' (ask for money)?", options: ["Me", "Partner", "Equal billing"] },
    { id: 3, text: "Who shouts loudest when NEPA brings light?", options: ["Me", "Partner", "We have inverter"] },
    { id: 4, text: "Who is more scared of their Nigerian mother?", options: ["Me", "Partner", "Both terrified"] },
    { id: 5, text: "Who is better at pricing/haggling in the market?", options: ["Me", "Partner", "We get scammed"] },
    { id: 6, text: "Who eats the most food?", options: ["Me", "Partner", "Equal gluttons"] },
    { id: 7, text: "Who is more 'Ajebutter' (soft life)?", options: ["Me", "Partner", "Both represent the trenches"] },
    { id: 8, text: "Who is more likely to fight a conductor/driver?", options: ["Me", "Partner", "We avoid wahala"] },
    { id: 9, text: "Who spends more time on TikTok/Instagram?", options: ["Me", "Partner", "Both addicted"] },
    { id: 10, text: "Who is more likely to say 'It is well' when things go wrong?", options: ["Me", "Partner", "Both"] },
    { id: 11, text: "Who is more likely to forget to reply to messages?", options: ["Me", "Partner", "Intentional ignoring"] },
    { id: 12, text: "Who is more dramatic (Nollywood style)?", options: ["Me", "Partner", "Both"] },
    { id: 13, text: "Who sleeps off during movies?", options: ["Me", "Partner", "Both"] },
    { id: 14, text: "Who is more likely to dance at a wedding for food?", options: ["Me", "Partner", "Both"] },
    { id: 15, text: "Who complains more about Nigeria?", options: ["Me", "Partner", "We're tired"] },
    { id: 16, text: "Who knows more Afrobeats lyrics?", options: ["Me", "Partner", "Equal"] },
    { id: 17, text: "Who eats the meat before finishing the rice?", options: ["Me", "Partner", "Sacrilege!"] },
    { id: 18, text: "Who checks their phone first in the morning?", options: ["Me", "Partner", "Both"] },
    { id: 19, text: "Who is better at lying?", options: ["Me", "Partner", "We are honest"] },
    { id: 20, text: "Who buys more Suya/Street food?", options: ["Me", "Partner", "Equal"] },
    { id: 21, text: "Who is more suspicious (looks through phones)?", options: ["Me", "Partner", "We trust each other"] },
    { id: 22, text: "Who creates the most memes/stickers?", options: ["Me", "Partner", "None"] },
    { id: 23, text: "Who is likely to say 'God When' on IG?", options: ["Me", "Partner", "Both"] },
    { id: 24, text: "Who is more likely to forget their wallet?", options: ["Me", "Partner", "Both"] },
    { id: 25, text: "Who spends more on Data/Airtime?", options: ["Me", "Partner", "WiFi only"] },
    { id: 26, text: "Who attracts more drama?", options: ["Me", "Partner", "We are peaceful"] },
    { id: 27, text: "Who is the designated driver?", options: ["Me", "Partner", "Uber/Bolt"] },
    { id: 28, text: "Who is more likely to trip in public?", options: ["Me", "Partner", "Both clumsy"] },
    { id: 29, text: "Who has a weirder laugh?", options: ["Me", "Partner", "Both"] },
    { id: 30, text: "Who takes longer to reply to texts?", options: ["Me", "Partner", "Instant replies"] }
  ],
  deep: [
    { id: 1, text: "Who is more serious about 'meeting the parents'?", options: ["Me", "Partner", "Already met"] },
    { id: 2, text: "Who talks about marriage/future more?", options: ["Me", "Partner", "Both"] },
    { id: 3, text: "Who handles family pressure better?", options: ["Me", "Partner", "Neither"] },
    { id: 4, text: "Who is more likely to Japa (relocate)?", options: ["Me", "Partner", "We go together"] },
    { id: 5, text: "Who is more religious/prayerful?", options: ["Me", "Partner", "Equal"] },
    { id: 6, text: "Who saves money better?", options: ["Me", "Partner", "We both spend"] },
    { id: 7, text: "Who is more ambitious/hustler?", options: ["Me", "Partner", "Both"] },
    { id: 8, text: "Who is more traditional?", options: ["Me", "Partner", "Equal"] },
    { id: 9, text: "Who gives better advice?", options: ["Me", "Partner", "Equal"] },
    { id: 10, text: "Who is more likely to compromise?", options: ["Me", "Partner", "Equal"] },
    { id: 11, text: "Who holds a grudge longer?", options: ["Me", "Partner", "Neither"] },
    { id: 12, text: "Who is more emotionally mature?", options: ["Me", "Partner", "Equal"] },
    { id: 13, text: "Who is the better listener?", options: ["Me", "Partner", "Equal"] },
    { id: 14, text: "Who supports the other's dreams more?", options: ["Me", "Partner", "Equal"] },
    { id: 15, text: "Who is more optimistic about the relationship?", options: ["Me", "Partner", "Both"] },
    { id: 16, text: "Who is more willing to go to therapy?", options: ["Me", "Partner", "Neither"] },
    { id: 17, text: "Who values tradition over modern life?", options: ["Me", "Partner", "Both"] },
    { id: 18, text: "Who would sacrifice career for family?", options: ["Me", "Partner", "Both"] },
    { id: 19, text: "Who fears failure more?", options: ["Me", "Partner", "Both"] },
    { id: 20, text: "Who needs more validation/affirmation?", options: ["Me", "Partner", "Equal"] },
    { id: 21, text: "Who is more likely to keep a secret?", options: ["Me", "Partner", "Both"] },
    { id: 22, text: "Who judges people more?", options: ["Me", "Partner", "Neither"] },
    { id: 23, text: "Who is more stubborn?", options: ["Me", "Partner", "Both"] },
    { id: 24, text: "Who handles change better?", options: ["Me", "Partner", "Neither"] },
    { id: 25, text: "Who is more generous with money?", options: ["Me", "Partner", "Equal"] },
    { id: 26, text: "Who is more protective of their privacy?", options: ["Me", "Partner", "Both"] },
    { id: 27, text: "Who is more likely to forgive cheating?", options: ["Me", "Partner", "Hell no"] },
    { id: 28, text: "Who cares more about what people think?", options: ["Me", "Partner", "Neither"] },
    { id: 29, text: "Who is more adventurous?", options: ["Me", "Partner", "Equal"] },
    { id: 30, text: "Who is the 'rock' in the relationship?", options: ["Me", "Partner", "Shared role"] }
  ]
};
